---
apiVersion: v1
kind: Secret
metadata:
  name: mandibuswell-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/mandibuswell-gateway-gitops
